export const defaultUnits = [
  { id: "icu-alpha", name: "ICU Alpha Pod", type: "Critical Care" },
  { id: "ed-obs", name: "Emergency Observation", type: "Emergency" },
  { id: "onc-day", name: "Oncology Day Hospital", type: "Inpatient" },
];

export const defaultMasterData = [
  {
    id: "proc-preoxygenation",
    type: "procedures",
    name: "Preoxygenation & Airway Assessment",
    category: "Airway & Respiratory",
    summary: "Standardized airway readiness check for emergent intubations.",
    content: {
      description: "Evidence-based readiness workflow for crash airway support.",
      definition: "Nursing-led bundle to optimize oxygenation reserves and equipment.",
      indications: ["Impending airway compromise", "Rapid sequence intubation"],
      contraindications: ["Crash airway without resources"],
      equipment: ["Bag-valve-mask", "PEEP valve", "Capnography"],
      steps: [
        "Run LEMON airway assessment and announce timeout.",
        "Apply monitoring and elevate head of bed.",
        "Deliver 100% oxygen for ≥3 minutes or until SpO2 ≥ 98%.",
      ],
      safetyAlerts: ["Abort if saturation falls below 93% despite optimization."],
    },
  },
  {
    id: "proc-bvm",
    type: "procedures",
    name: "Bag-Valve-Mask Ventilation",
    category: "Airway & Respiratory",
    summary: "Controlled manual ventilation for apnea or peri-intubation care.",
    content: {
      description: "Protective ventilation technique with waveform monitoring.",
      indications: ["Respiratory arrest", "Procedural sedation"],
      equipment: ["Self-inflating bag", "Oral airway", "PEEP valve"],
      steps: [
        "Position airway and insert adjuncts.",
        "Deliver 6-8 mL/kg tidal volumes at 10 breaths/min.",
        "Monitor ETCO2 and avoid gastric insufflation.",
      ],
      safetyAlerts: ["Target ETCO2 35-45 mmHg.", "Use viral filter for airborne isolation."],
    },
  },
  {
    id: "proc-central-line",
    type: "procedures",
    name: "Central Venous Catheter Maintenance",
    category: "Vascular Access",
    summary: "Maintenance checklist for tunneled and temporary lines.",
    content: {
      description: "Sterile technique and surveillance bundle.",
      steps: [
        "Perform scrub-the-hub for 15 seconds.",
        "Assess insertion site and dressing integrity.",
        "Document patency, blood return, and line necessity.",
      ],
      safetyAlerts: ["Hold infusions if suspect CLABSI and escalate."],
    },
  },
  {
    id: "lab-lactate",
    type: "labs",
    name: "Serum Lactate",
    category: "Chemistry",
    summary: "Perfusion trend tracking for sepsis bundles.",
    content: {
      unit: "mmol/L",
      normalRange: "0.5-2.0",
      criticalHigh: ">4.0",
      interpretation: "Rising trend suggests inadequate perfusion.",
    },
  },
  {
    id: "lab-potassium",
    type: "labs",
    name: "Potassium",
    category: "Chemistry",
    summary: "Electrolyte monitoring for arrhythmia prevention.",
    content: {
      unit: "mEq/L",
      normalRange: "3.5-5.0",
      criticalLow: "<2.5",
      criticalHigh: ">6.5",
    },
  },
  {
    id: "lab-inr",
    type: "labs",
    name: "INR",
    category: "Hematology",
    summary: "Coagulation monitoring for anticoagulated patients.",
    content: {
      unit: "ratio",
      normalRange: "0.8-1.2",
      criticalHigh: ">4.0",
    },
  },
  {
    id: "drug-norepinephrine",
    type: "drugs",
    name: "Norepinephrine",
    category: "Vasoactive",
    summary: "First-line vasopressor for distributive shock.",
    content: {
      concentration: "4 mg in 250 mL D5W",
      doseRange: "0.02-1 mcg/kg/min",
      titration: "Adjust q2min to target MAP 65 mmHg",
      safetyAlerts: ["Use central line when available", "Monitor for digital ischemia"],
    },
  },
  {
    id: "drug-ketamine",
    type: "drugs",
    name: "Ketamine",
    category: "Sedation",
    summary: "Dissociative anesthetic with preserved airway reflexes.",
    content: {
      bolus: "0.5-1 mg/kg IV", 
      infusion: "0.5-4 mg/kg/hr",
      considerations: ["Monitor for emergence reactions", "Maintain airway support"],
    },
  },
  {
    id: "assessment-braden",
    type: "assessments",
    name: "Braden Scale",
    category: "Skin Integrity",
    summary: "Pressure injury risk assessment scored across six domains.",
    content: {
      scoring: "≤12 high risk, 13-14 moderate",
      cadence: "Every shift and with condition changes",
      actions: ["Turn q2h", "Moisture control", "Support surface"],
    },
  },
  {
    id: "assessment-nirs",
    type: "assessments",
    name: "Neurologic In-room Surveillance",
    category: "Neuro",
    summary: "Bedside neuro change detection bundle.",
    content: {
      cadence: "Every 1 hour for high-risk neurologic patients",
      components: ["LOC", "Pupils", "Motor strength", "Speech"],
      escalation: "Notify provider for ≥2 point NIHSS change",
    },
  },
];
